#!/bin/bash

########################################################################
#                                                                      #
#  build-video: build a new video from the extracted component files   #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to build a new video from the extracted, and modified
# component files generated in earlier steps. This video is the final
# product, without the proper filename. Since there is the potential to
# make multiple source videos, and/or various versions of the subtitles
# this script will require a separate launcher to handle the logic of
# selecting the source files for each final version.
#
# Accepts no arguments:
#
# Reads fixvid.conf for:
#         video_title   Name of the video
#         work_files    Filename prefix for working files
#
# Displays the ffmpeg progress line while running amd the results of the
# time command once finished.
#
# Generates 1 file:
#     *_codec_<video_label>.mkv  The newly created video.
#

# Load the configuration file
test -s fixvid.conf && . fixvid.conf || return 4;

# Set the output filename base
movie_prefix="${work_files}_full_${video_codec}_${video_label}";

# Skip this if it has already been done.
# To rerun, delete the *_video.mkv file first
if [ -s "${movie_prefix}.mkv" ]; then
  return;
fi

# Add the video component (always available)
source_list="$input_flags -i \
'${work_files}_video_${video_codec}_${video_label}.mkv'";
stream_list="-map $source_count:0 -c:$stream_count copy \\
-metadata:s:$stream_count language=eng \
-metadata:s:$stream_count title='$video_title' \\
-disposition:$stream_count +default";
source_count=$((++source_count));
stream_count=$((++stream_count));

# Add the enhanced stereo component (always available)
source_list="$source_list \\
$input_flags -i '${work_files}_stereo_adjusted.aac'";
stream_list="$stream_list \\
-map $source_count:0 -c:$stream_count copy \\
-metadata:s:$stream_count language=eng \
-metadata:s:$stream_count title='Stereo' \\
-disposition:s:$stream_count default";
source_count=$((++source_count));
stream_count=$((++stream_count));

# Add in the subtitles
# All versions get all available subtitle streams
unset subs_default;
subs_group=1;
check_var="subs_source_$subs_group";
while [[ ${!check_var} ]]; do
  for item in label title included SDH; do
    param_var="subs_${item}_${subs_group}";
    declare subs_$item="${!param_var}";
  done
  if [[ $subs_included ]]; then
    source_list="$source_list \\
    $input_flags -i '${work_files}_subs_${subs_label}.ass'";
    stream_list="$stream_list \\
    -map $source_count:0 -c:$stream_count copy \\
    -metadata:s:$stream_count language=eng \
    -metadata:s:$stream_count title='$subs_title'";
    if [[ $subs_SDH ]]; then
      stream_list="$stream_list \\
      -disposition:$stream_count hearing_impaired";
    fi
    if [[ $subs_default ]]; then
      stream_list="$stream_list \\
      -disposition:$stream_count -default";
    else
      stream_list="$stream_list \\
      -disposition:$stream_count +default";
      subs_default=$ubs_group;
    fi
    source_count=$((++source_count));
    stream_count=$((++stream_count));
  fi
  ((subs_group++));
  check_var="subs_source_$subs_group";
done

# Add the chapter source file, if any
if [[ $chapter_file ]] && [[ -s $chapter_file ]]; then
  source_list="$source_list \\
  -i '$chapter_file'";
  stream_list="$stream_list \\
  -map_chapters $source_count";
  source_count=$((++source_count));
  stream_count=$((++stream_count));
fi

cat <<EOCMD > "$cmd_file";
FFREPORT=file=${log_file}:level=40 \\
ffmpeg -hide_banner -loglevel quiet -stats -y \\
$source_list \\
$stream_list \\
-metadata creation_time=$timestamp \\
-metadata title='$title' \\
$use_threads $output_flags "${movie_prefix}.mkv";
EOCMD

# Set the filename base for the command and log files
control_prefix="fixvid_${movie_prefix}";

cat <<EOC >"$control_prefix.cmd";
FFREPORT=file='$control_prefix.log':level=40 \\
ffmpeg -hide_banner -loglevel error -stats -y \\
$video_input $stereo_input $subs_input \\
$video_output $stereo_output $subs_output \\
$video_data $stereo_data $subs_data \\
$strip_meta \\
-metadata language=eng  -metadata title='$video_title' \\
$use_threads $output_flags "${movie_prefix}.mkv";

EOC

# Make the newly created file executable
# chmod +x "$control_prefix.cmd";

# Execute the just-made ffmpeg command
# time ./"$control_prefix.cmd";

cat "$control_prefix.cmd";
