#!/bin/bash

########################################################################
#                                                                      #
#  build-video: build a new video from the extracted component files   #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to build a new video from the extracted, and modified
# component files generated in earlier steps. This video is the final
# product, without the proper filename. Since there is the potential to
# make multiple source videos, and/or various versions of the subtitles
# this script will require a separate launcher to handle the logic of
# selecting the source files for each final version.
#
# Accepts no arguments:
#
# Reads fixvid.conf for:
#         video_title   Name of the video
#         work_files    Filename prefix for working files
#
# Displays the ffmpeg progress line while running amd the results of the
# time command once finished.
#
# Generates 1 file:
#     *_codec_<video_label>.mkv  The newly created video.
#

# Load the configuration file
test -s fixvid.conf && . fixvid.conf || return 4;

# Set the proper codec for ffmpeg use from that supplied
v_codec=${video_codec,,};

# Set the output filename base
movie_prefix="${work_files}_full_${video_codec}_${video_label}";

# Skip this if it has already been done.
# To rerun, delete the *_video.mkv file first
if [ -s "${movie_prefix}.mkv" ]; then
  return;
fi

video_file="${work_files}_video_${video_codec}_${video_label}.mkv";
video_input="$input_flags -i $video_file";
video_output="-map 0:0 -c:0 copy";
video_data="-metadata:s:0 language=eng";
video_data="$video_data -metadata:s:0 title='$video_title'";
stereo_file="${work_files}_stereo_adjusted.aac";
stereo_input="$input_flags -i $stereo_file";
stereo_output="-map 1:0 -c:a copy";
stereo_data="-metadata:s:1 language=eng";
stereo_data="$stereo_data -metadata:s:1 title='Enhanced Stereo'";
if [[ $subs_label ]]; then
  subs_file="${work_files}_subs_${subs_label}.ass";
  subs_input="$input_flags -i $subs_file";
  subs_output="-map 2:0 -c:s copy";
  subs_data="-metadata:s:2 language=eng"
  subs_data="$subs_data -metadata:s:2 title='$subs_title'";
else
  subs_input="";
  subs_output="";
  subs_data="";
fi

# Set the filename base for the command and log files
control_prefix="fixvid_${movie_prefix}";

cat <<EOC >"$control_prefix.cmd";
FFREPORT=file='$control_prefix.log':level=40 \\
ffmpeg -hide_banner -loglevel error -stats -y \\
$video_input $stereo_input $subs_input \\
$video_output $stereo_output $subs_output \\
$video_data $stereo_data $subs_data \\
$strip_meta \\
-metadata language=eng  -metadata title='$video_title' \\
$use_threads $output_flags "${movie_prefix}.mkv";

EOC

# Make the newly created file executable
chmod +x "$control_prefix.cmd";

# Execute the just-made ffmpeg command
time ./"$control_prefix.cmd";
