#!/bin/bash

########################################################################
#                                                                      #
#  config-template: used to create the fixvid.conf file by init        #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

# This file is copied, as fixvid.conf, into the working directory



########################################################################
#
# Chapter titles are a special case. Chapter information is embedded in
# the container rather than the stream(s). The process of creating the
# component files is designed to strip out all the meta data from the
# streams, and the chapter titles are "lost" in the process. So many of
# the videos encountered so far have had meaningless 'title' for the
# chapters. Either the chapter number, or the chapter start time, is the
# common 'title,' and loosing those is of no consequence. Attempting to
# preserve the title in the processing turns out to be more work than to
# just add them back into the final product, when they exist.
#
# Name of the file that has useful chapter data. Leave commented if none
# chapter_file='movie';

########################################################################
#
#                        Video component settings
# File that has the video to use as the source for the final product
video_source='movie';
video_stream=0;

# An extra label for the video extract file to separate one extraction
# from the rest. Resolution is a common choice here.
video_label_1="1080p";

# The codec to use in the final product, HEVC or H264 for me
video_codec_1='HEVC';

# The extra parameters to pass to the video encoder
# This parameter is expected to exist

# HEVC (nVidia) uses these, with adjustments as needed
video_params_1='-preset slow -2pass 1 -rc constqp -qp 28 -rc-lookahead 32 -level 5.1 -profile:v main -tier high';
# Add -pix_fmt to drop from 10-bit to 8-bit
# video_params_1='-preset slow -2pass 1 -rc constqp -qp 28 -rc-lookahead 32 -level 5.1 -profile:v main -tier high -pix_fmt yuv420p';

# H264 (nVidia) uses these, with adjustments as needed
# video_params_1="-preset slow -2pass 1 -rc constqp -qp 22 -rc-lookahead 32 -level 5.1 -profile:v high";
# Add -pix_fmt to drop from 10-bit to 8-bit
# video_params_1="-preset slow -2pass 1 -rc constqp -qp 22 -rc-lookahead 32 -level 5.1 -profile:v high" -pix_fmt yuv420p';

# Equalizer adjustments to the video. Options include:
#     contrast, float: -2.0 to 2.0, default 1
#     brightness, float: -1.0 to 1.0, default 0
#     saturation, float: 0.0 to 3.0, default 1
#     gamma, float: 0.1 to 10.0, default 1
#     gamma_r, (red)float: 0.1 to 10.0, default 1
#     gamma_g, (green)float: 0.1 to 10.0, default 1
#     gamma_b, (blue)float: 0.1 to 10.0, default 1
#     gamma_weight, float: 0.0 to 1.0, default 1, (level of effect)
# This paramater is optional, uncomment if needed
# video_equalizer_1='eq=contrast=1.12:brightness=0.18';

# Adjustments to the video's resolution, size, aspect ratio, etc., and
# any other filtering needed. It can be simple, as passed to the -vf of
# ffmpeg, or complex, as part of a complete fiter graph for ffmpeg's
# -filter_complex. If the complex version is used the filter graph must
# have, exactly one input pad, [VIN] and exactly one output pad [VOUT],
# and the video_complex_1 must be set. For the simple versions there are
# no input/output pads, and video_complex_1 must be commented out. There
# should be no single quotes used in either version of the filter
# This parameter is optional, uncomment if needed
# video_adjust_1='scale=1920x796,setsar=1/1';
# video_adjust_1='crop=1920:754,scale=1280x504,setsar=1/1';
# video_adjust_1='[VIN] scale=1920x796,setsar=1/1 [VOUT]';
# video_adjust_1='[VIN] crop=1920:754 [CROP];[CROP] scale=1280x504,setsar=1/1 [VOUT]';
# This parameter is optional, uncomment if needed, see above
# video_complex_1=1;

# A second, third, etc. group of settings can be used by repeating the
# set of variables above, replacing the digit "1" with "2", and so on.
# The program will look for each, in sequence, and stop on the first one
# not found: group 3 will be ignored unless there is a group 2, etc.
# video_label_2='1080p';
# video_codec_2='H264';
# video_params_2="-preset slow -2pass 1 -rc constqp -qp 22 -rc-lookahead 32 -level 4.1 -profile:v high";
# Add -pix_fmt to drop from 10-bit to 8-bit
# video_params_2="-preset slow -2pass 1 -rc constqp -qp 22 -rc-lookahead 32 -level 4.1 -profile:v high -pix_fmt yuv420p";
# video_equalizer_2='';
# video_adjust_2='';
# video_complex_2=1;

########################################################################
#
#                        Audio component settings
#
# File that has the audio to use as source for the final stereo stream
# stereo_source='movie';
stereo_stream=1;

# File that has the audio to use as source for the final surround stream
# surround_source='movie';
surround_stream=1;

### Use for 7.1 surround sound
channel_map_71='channelmap=0-FL|1-FR|2-FC|3-LFE|4-BL|5-BR|6-SL|7-SR:7.1';
stereo_mix_71='pan=stereo|FL < 1.7*FC + 0.7*FL + 0.5*BL + 0.6*SL|FR < 1.7*FC + 0.7*FR + 0.5*BR + 0.6*SR';
channel_list_71='fl fr fc lf bl br sl sr';

### Use for 5.1 surround sound
channel_map_51='channelmap=0-FL|1-FR|2-FC|3-LFE|4-BL|5-BR:5.1';
stereo_mix_51='pan=stereo|FL < 1.7*FC + 0.6*FL + 0.5*BL|FR < 1.7*FC + 0.6*FR + 0.5*BR';
channel_list_51='fl fr fc lf bl br';

### Use for 5.1(side) surround sound
channel_map_51_side='channelmap=0-FL|1-FR|2-FC|3-LFE|4-SL|5-SR:5.1(side)';
stereo_mix_51_side='pan=stereo|FL < 1.7*FC + 0.5*FL + 0.6*SL|FR < 1.7*FC + 0.5*FR + 0.6*SR';
channel_list_51_side='fl fr fc lf sl sr';


# SETTINGS for dynaudnorm filter
#################################
# f frame-size(ms)[10-8000,500]: size of each frame for gain
#   calculations
# g Gaussian filter window size(frames)[3-301(odd),31]: the "window"
#   over which gain is normalized
# p peak target(%of FS)[.01-.99,.95]: the target max volume of
#   normalization.
# m max-gain[1-100,10]: globally applied limit to gain applied to any
#   segment.
# r RMS[0.0(disabled)-1.0]: Use RMS calculations, rather than "peak" for
#   gain factors
# s compression factor[0.0(disabled)-30.0]: lower is more dynamic
#   compression, 3 seems a hard no-distortion floor.

dyna_stereo='dynaudnorm=f=300:g=23:p=0.95:m=30:s=20';
dyna_center='dynaudnorm=f=100:g=13:p=0.97:m=15:s=20';
dyna_front='dynaudnorm=f=250:g=23:p=0.89:m=15:s=20';
dyna_surround='dynaudnorm=f=500:g=31:p=0.80:m=15:s=20';



########################################################################
#
#                        Subtitle component settings
#
# File that has the subtitles to use as the final subtitle stream
# subs_source_1='movie';
subs_stream_1=2;

# The label used in the filename to separate one set of subtitles from
# any others.
# For text-based subtitles, will also be used as the suffix for the
# final product as the generated subtitles are saved in external ASS and
# SRT files for use in players which need them. File name will be
# something like:
#       The_Movie_Name-CHI.srt
# for the case of subs_label set to CHI. The one exception to this is if
# the subs_label value is exactly DEFAULT, in which case the suffix will
# omitted. Many video players will take a subtitle file with the same
# name as the video file and consider them to be the set to load
# automatically
subs_label_1='DEFAULT';

# The 3-letter language code for the language the subtitles are in
subs_lang_1='eng';

# The title of the subtitles, as shown by most media players when the
# user selects subtitles from the menu
subs_title_1='Standard subtitles';
# What type of subtitles the souce file contains. Text is for SRT, AAS,
# and ASS.
subs_type_1='dvd_subtitle';
# Are these subtitles to be included in the final product video?
# Leave commented to prevent them from being included.
subs_included_1=1;

# Setting to show that this is a 'Hearing-Impaired' subtitle stream.
# Not required, but having it set will allow the stream to be marked as
# Hearing-Impaired in the final product in the event that a player is
# set up to always choose such subtitles over other defaults.
# subs_SDH_1=1;

# Additional sets of subtitles may be created by using increasing
# numbers for each set of parameters. All parameters are needed for the
# system to create the subtitles described.
# subs_source_2='movie.mkv';
# subs_stream_2=3;
# subs_label_2='DEFAULT';
# subs_title_2='Standard Subtitles';
# subs_type_2='text';
# subs_included_2=1;
# subs_SDH_2=1;

# Flag to allow converting to the nVidia encoders
enable_nvidia=true;


#######################################################################
#
#                  The most often changed values
#  Set to make the system work "as-is" but not very informative

# How many parallel processes to run, when using parallelism
# Set to 1 to disable parallel processing, i.e. 1 at a time
max_parallel=8;

# For surround sound souces, uncomment the correct layout below

# surround_layout='7.1';
# surround_layout='5.1';
surround_layout='5.1(side)';

# The "time" when this was all collected and remuxed.
timestamp=2018-10-31T13:21:08.69Z;

# Year the video was produced/released
video_year=2018;

# Name used as the prefix for work files, use shell-safe names
work_files="stream";

# Name used as the prefix for the final product files, stay shell-safe
final_files="Final";

# Name of the video that is stored in the meta data of the files.
# To use a double quote in the title use triple-escape, \\\"
video_title="Video Title";

video_lang="eng";
