#!/bin/bash

# This file is copied, as fixvid.conf, into the working directory

# Name used as the prefix for work files
#
# !! The string in _mostly_ safe, but will break on appostraphes
# Still, it's better to keep things "shell-safe"
#
work_files='';

# Name used as the prefix for the final product files
#
# !! The string in _mostly_ safe, but will break on appostraphes
# Still, it's better to keep things _shell-safe_
#
final_files='';

# Year the video was produced/released
video_year='';

# Name of the video that is stored in the meta data of the files.
#
# !! The string in _mostly_ safe, but will break on appostraphes
#
video_title='';

########################################################################
#
#                        Video component settings
#
#  File that has the video to use as the source for the final product
video_source='';
video_stream=0;

# An extra label for the video extract file to separate one extraction
# from the rest. Resolution is a common choice here.
video_label_1="1080p";

# The codec to use in the final product, HEVC or H2264 for me
video_codec_1='HEVC';

# The extra parameters to pass to the video encoder
# HEVC (nVidia) uses these, with adustments as needed
# This parameter is expected to exist
video_params_1='-preset slow -2pass 1 -rc constqp -qp 28 -rc-lookahead 32 -level 4.1 -profile:v main -tier high';
# H264 (nVidia) uses these, with adjustments as needed
# video_params_1="-preset slow -2pass 1 -rc constqp -qp 22 -rc-lookahead 32 -level 4.1 -profile:v high";

# Equalizer adjustments to the video. Options include:
#     contrast, float: -2.0 to 2.0, default 1
#     brightness, float: -1.0 to 1.0, default 0
#     saturation, float: 0.0 to 3.0, default 1
#     gamma, float: 0.1 to 10.0, default 1
#     gamma_r, (red)float: 0.1 to 10.0, default 1
#     gamma_g, (green)float: 0.1 to 10.0, default 1
#     gamma_b, (blue)float: 0.1 to 10.0, default 1
#     gamma_weight, float: 0.0 to 1.0, default 1, (level of effect)
# This paramater is optional, uncomment if needed
video_equalizer_1='eq=contrast=1.12:brightness=0.18';

# Adjustments to the video's resolution, size, aspect ratio, etc., and
# any other filtering needed. It can be simple, as passed to the -vf of
# ffmpeg, or complex, as part of a complete fiter graph for ffmpeg's
# -filter_complex. If the complex version is used the filter graph must
# have, exactly one input pad, [VIN] and exactly one output pad [VOUT],
# and the video_complex_1 must be set. For the simple versions there are
# no input/output pads, and video_complex_1 must be commented out. There
# should be no single quotes used in either version of the filter
# This paramater is optional, uncomment if needed
# video_adjust_1='scale=1920x796,setsar=1/1';
# This paramater is optional, uncomment if needed, see above
# video_complex_1="1";

# A second, third, etc. group of settings can be used by repeating the
# set of variables above, replacing the digit "1" with "2", and so on.
# The program will look for each, in sequence, and stop on the first one
# not found: group 3 will be ignored unless there is a group 2, etc.
video_label_2="TVHD";
video_codec_2='H264';
video_params_2="-preset slow -2pass 1 -rc constqp -qp 22 -rc-lookahead 32 -level 4.1 -profile:v high";
video_equalizer_2='eq=contrast=1.12:brightness=0.18';
video_adjust_2='scale=1920x796,setsar=1/1';
video_complex_2="1";

########################################################################
#
#                        Audio component settings
#
# File that has the audio to use as source for the final stereo stream
stereo_source='';
stereo_stream=1;

# File that has the audio to use as source for the final surorund stream
surround_source='';
surround_stream=1;

### Use for 5.1 surround sound
# surround_layout='5.1';
# channels='channelmap=0-FL|1-FR|2-FC|3-LFE|4-BL|5-BR:5.1';
# stereo_mix='pan=stereo|FL < 1.7*FC + 0.5*FL + 0.5*BL|FR < 1.7*FC + 0.5*FR + 0.5*BR';

### Use for 5.1(side) surround sound
# surround_layout='5.1(side)';
# channels='channelmap=0-FL|1-FR|2-FC|3-LFE|4-SL|5-SR:5.1(side)';
# stereo_mix='pan=stereo|FL < 1.7*FC + 0.5*FL + 0.5*SL|FR < 1.7*FC + 0.5*FR + 0.5*SR';


# SETTINGS for dynaudnorm filter
#################################
# f frame-size(ms)[10-8000,500]: size of each frame for gain
#   calculations
# g Gaussian filter window size(frames)[3-301(odd),31]: the "window"
#   over which gain is normalized
# p peak target(%of FS)[.01-.99,.95]: the target max volume of
#   normalization.
# m max-gain[1-100,10]: globally applied limit to gain applied to any
#   segment.
# r RMS[0.0(disabled)-1.0]: Use RMS calculations, rather than "peak" for
#   gain factors
# s compression factor[0.0(disabled)-30.0]: lower is more dynamic
#   compression, 3 seems a hard no-distortion floor.

dyna_stereo='dynaudnorm=f=300:g=23:p=0.95:m=30:s=30';
dyna_center='dynaudnorm=f=100:g=13:p=0.97:m=15:s=30';
dyna_front='dynaudnorm=f=250:g=23:p=0.89:m=15:s=30';
dyna_surround='dynaudnorm=f=500:g=31:p=0.80:m=15:s=30';



# Subtitle component settings
title_source='';
title_stream=0;
hi_title_source='';
hi_title_stream=0;


timestamp='1993-08-13T13:07:08.69Z';

# Flag to allow converting to the nVidia encoders
enable_nvidia=true;
