#!/bin/bash

########################################################################
#                                                                      #
#  dts-build: create DTS sound files from AAC/ACS files                #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to create surround sound files in the DTS format using
# the previously created AC3 files. Will only create both the reqular
# and adjusted versions if both versions exist in AC3 format. If either
# version is missing, the script will abort.
#
# Accepts no arguments.
#
# Reads fixvid.conf for:
#     work_files      the prefix of filenames for work files
#     video_title     added to the title metadata of the files
#     timestamp       entered in the creation_time metadata for streams
#
# Displays the ffmpeg progress line while running amd the results of the
# time command once finished.
#
# Generates 4 files:
#     fixvid_*_dts.cmd         The complete ffmpeg command to execute
#     fixvid_*_dts.log         The captured output of the ffmpeg command
#     *_surround.dts           The original soundtrack
#     *_surround_adjusted.dts  The adjusted soundtrack
#

# Load the configuration file
test -s fixvid.conf && . fixvid.conf || exit 4;

# Set the output filename base
surround_prefix="${work_files}_surround";

# Skip this if it has already been done.
# To rerun, delete the *_stereo_adjusted.aac file first
if [ -s "${surround_prefix}_adjusted.dts" ]; then
  exit;
fi

if [ ! -s ${surround_prefix}.ac3 ] || [ ! -s ${surround_prefix}_adjusted.ac3 ]; then
  exit;
fi

time bash -c "FFREPORT=file=\"fixvid_${surround_prefix}.log\":level=40 \
ffmpeg -hide_banner -y -loglevel error -stats \
$input_flags -i '${surround_prefix}.ac3' \
$input_flags -i '${surround_prefix}_adjusted.ac3' \
-map 0:0 \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Surround Sound' \
-c:0 dts -b:a 768k -strict -2 \
$use_threads $output_flags \
\"${surround_prefix}.dts\" \
-map 1:0 \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Surround Sound (Enhanced)' \
-c:0 dts -b:a 768k -strict -2 \
$use_threads $output_flags \
\"${surround_prefix}_adjusted.dts\"";
