#!/bin/bash

########################################################################
#                                                                      #
#  dts-build: create DTS sound files from AAC/ACS files                #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to create surround sound files in the DTS format using
# the previously created AC3 files. Will only create both the regular
# and adjusted versions if both versions exist in AC3 format. If either
# version is missing, the script will abort.
#
# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Load the helper functions and common settings
source "$fixvid_dir/helpers";

group='audio';
required='dts';
group_fields="source stream label title lang layout channels include \
dyna_center dyna_extras dyna_origin dyna_stereo mapping mixing";

function do_dts_build {
  # Test for surround sound and load surround sound settings
  surround_sound_settings || return 0;

  # Select which source file type to use, AC3 or AAC
  source_ext='ac3';
  [[ 1 = $skip_ac3 ]] && [[ 1 = $skip_aac ]] && return 0;
  [[ 1 = $skip_ac3 ]] || source_ext='aac';

  # Skip this if it has already been done.
  # To rerun, delete the *-remix.dts file first
echo "building $group_num";
  [[ -s "${work_prefix}-remix.dts" ]] && return 0;

  # Check for all dependent files
  # Force hts-remix to (re)make all if one is missing
  files_ready=0;
  [[ -s "${work_prefix}-remix.$source_ext" ]] || files_ready=1;
  [[ -s "${work_prefix}.$source_ext" ]] || files_ready=1;
  [[ 0 = $files_ready ]] || {
    rm -f "${work_prefix}-remix.aac";
    rm -f "${work_prefix}-remix.ac3";
    echo "Source file(s) not found.";
    echo " ... Creating ...";
    echo "";
    "$fixvid_dir/hts-remix" $group_num;
  }

  # Skip creation of the un-normalized remix if already done
  [[ -s "${work_prefix}.dts" ]] || multi_launch "Create ${audio_label} DTS" bash -c "FFREPORT=file='fixvid-${work_prefix}.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}.$source_ext' -map 0:0 $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_label DTS' -c:0 dts -b:a 768k -strict -2 $use_threads $output_flags '${work_prefix}.dts'";

  # Always (re-)create the normalized version
  multi_launch "Remix ${audio_label} DTS" bash -c "FFREPORT=file='fixvid-${work_prefix}.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '${work_prefix}-remix.$source_ext' -map 0:0 $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_label DTS' -c:0 dts -b:a 768k -strict -2 $use_threads $output_flags '${work_prefix}-remix.dts'";
}

# Read the optional argument.
[[ $1 ]] && target_num=$1 || target_num=0;

process_group do_dts_build $group $required $target_num $group_fields;

wait;
