#!/bin/bash

########################################################################
#                                                                      #
#  extract-video: script to extract one version of the video           #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to extract the video component from the source file and
# apply any adjustments to it while creating a video-only file for use
# in building the final product. Because of the need to make multiple
# versions of the video, for evaluation purposes, this will require a
# separate launcher with the ability to discriminate the variables from
# the config file and options from the command line.
#

# Set the proper codec for ffmpeg to use from that supplied
v_codec=${video_codec,,};
[[ $enable_nvidia ]] && [[ $v_codec =~ hevc|h264 ]] && v_codec="${v_codec}_nvenc";

# Set the output filename base
work_prefix="${work_files}-video-${video_codec}-${video_label}";

# Skip this if it has already been done.
# To rerun, delete the *_video.mkv file first
[[ -s "${work_prefix}.mkv" ]] && return 3;

# Build the video mapping and filter line
if [[ $video_adjust ]] && [[ $video_complex ]]; then
  # Always use the yadif 'yet another de-interlace filter' filter
  filtering="-filter_complex '[0:${video_stream}] yadif";
  # Apply the equalizer settings, if any
  [[ $video_equalizer ]] \
    && filtering="${filtering} [VEQ];[VEQ] ${video_equalizer}";
  # Add in the other adjustments to the video, should be for setting the
  # size, sar (screen aspect ratio), dar (display aspect ratio), etc.,
  # but can also be used for more complex effects, including cropping
  # and letterbox formatting, or removing old letterbox formatting.
  filtering="${filtering} [VIN];${video_adjust}' -map [VOUT]";
else
  # Always use the yadif 'yet another de-interlace filter' filter
  filtering="-vf 'yadif";
  # Apply the equalizer settings, if any
  [[ $video_equalizer ]] && filtering="${filtering},${video_equalizer}";
  # Add in the other adjustments to the video, should be for setting the
  # size, sar (screen aspect ratio), dar (display aspect ratio), etc.,
  # but can also be used for more complex effects, including cropping
  # and letterbox formatting, or removing old letterbox formatting.
  [[ $video_adjust ]] && filtering="${filtering},${video_adjust}";
  filtering="${filtering}' -map 0:$video_stream";
fi

time bash -c "FFREPORT=file='fixvid-${work_prefix}.log':level=40 \
ffmpeg -hide_banner -y -loglevel error -stats \
$input_flags -i '$video_source' \
$filtering \
$strip_meta_all $file_meta \
-metadata:s:0 language=$video_lang -metadata:s:0 title='$video_title' \
-c:0 $v_codec $video_params \
$video_only $use_threads $output_flags \
'${work_prefix}.mkv'";
