#!/bin/bash

########################################################################
#                                                                      #
#  extract-stereo: extract a stereo soundtrack from a souce and        #
#  modify it.                                                          #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to extract the stereo soundtrack from a source file,
# and save it in four files: AAC encoded and AC3 encoded versions of
# the 'original' soundtrack and the normalized version
#
# Because of the possibility of extracting multiple versions of the
# soundtrack, this will require a separate launcher with the ability to
# discriminate the variables from the config file and options from the
# command line.
#

# Set the output filename base
work_prefix="${work_prefix}-stereo";

# Skip this if it has already been done.
# To rerun, delete the *-norm.* files first
[[ 1 != $audio_make_ac3 ]] && \
[[ 1 != $audio_include_ac3 ]] && \
  extension='aac' || extension='ac3';
[[ -s "${work_prefix}-norm.$extension" ]] && return 3;


# Always make, or replace, the adjusted versions of the stereo files.
# They are subject to repeated building until the "correct" sound is
# achieved.

[[ 1 = $audio_make_aac ]] || \
[[ 1 = $audio_include_aac ]] && \
  multi_launch "${audio_label} Norm to AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-norm-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -af $audio_dyna_stereo -map 0:$audio_stream $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='${audio_title} (Enhanced)' -c:0 libfdk_aac -profile:a aac_he -b:a 128k $audio_only $use_threads $output_flags '${work_prefix}-norm.aac'";
[[ 1 = $audio_make_ac3 ]] || \
[[ 1 = $audio_include_ac3 ]] && \
  multi_launch "${audio_label} Norm to AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-norm-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -af $audio_dyna_stereo -map 0:$audio_stream $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='${audio_title} (Enhanced)' -c:0 ac3 -b:a 192k $audio_only $use_threads $output_flags '${work_prefix}-norm.ac3'";

# Skip creation of either, or both, of the un-normalized stereo versions
# if they have already been made. They are not "adjusted" in any way, so
# remaking them each time is wasted CPU cycles.

[[ 1 = $audio_make_aac ]] || \
[[ 1 = $audio_include_aac ]] && \
[[ ! -s "${work_prefix}.aac" ]] && \
  multi_launch "${audio_label} Copy to AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -map 0:$audio_stream $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='${audio_title}' -c:0 libfdk_aac -profile:a aac_he -b:a 128k $audio_only $use_threads $output_flags '${work_prefix}.aac'";
[[ 1 = $audio_make_ac3 ]] || \
[[ 1 = $audio_include_ac3 ]] && \
[[ ! -s "${work_prefix}.ac3" ]] && \
  multi_launch "${audio_label} Copy to AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -map 0:$audio_stream $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='${audio_title}' -c:0 ac3 -b:a 192k $audio_only $use_threads $output_flags '${work_prefix}.ac3'";
