#!/bin/bash

########################################################################
#                                                                      #
#  extract-subtitles-text: extract subtitles from a souce and create   #
#  an ASS file                                                         #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to extract the subtitles from a text-based file, such
# as an SRT or ASS file, or from an existing video file, and save them
# to a known named file for eventual inclusion in the finished product.
# Because of the need to make multiple versions of subtitles, this will
# require a separate launcher with the ability to discriminate the
# variables from the config file and options from the command line.
#

# Skip this if it has already been done.
# To rerun, delete the created .ass file first
[[ -s "${work_prefix}.ass" ]] && return 0;

multi_launch "Subtitles $subs_label" bash -c "FFREPORT=file=\
'fixvid-${work_prefix}.log':level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i '$subs_source' \
$strip_meta_all $file_meta \
-map 0:$subs_stream -metadata:s:0 language='$subs_lang' \
-c:0 ass \
$subtitles_only $use_threads $output_flags \
'$work_prefix.ass'";
