#!/bin/bash

########################################################################
#                                                                      #
#  fixvid: the central launch point for the FixVid system              #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

# Find the true directory for the fixvid code base, and share it below
# all other fixvid commands will now be callable from within the code as
# "$fixvid_dir/command"
fixvid_source="${BASH_SOURCE[0]}"

# Resolve $fixvid_source until the file is no longer a symlink
while [ -L "$fixvid_source" ]; do
  fixvid_dir="$( cd -P "$( dirname "$fixvid_source" )" && pwd )"
  fixvid_source="$(readlink "$fixvid_source")"
  # If $fixvid_source was a relative symlink, we need to resolve it
  # relative to the path where the symlink file was located
  [[ $fixvid_source != /* ]] && fixvid_source="$fixvid_dir/$fixvid_source"
done
export fixvid_dir="$( cd -P "$( dirname "$fixvid_source" )" && pwd )";

# Check for the existence of a command.
if [ -z $1 ]; then
  "$fixvid_dir/usage" $(basename $0);
  cat <<NOCMD | cat;

    No $(basename $0) command given.

    For available commands, use:
    $ $(basename $0) help


NOCMD
  exit;
fi

# Check for a valid command, meaning there is a same-named, executable
# file in the fixvid root directory.
command_check=$1;
shift;

if [ "xhelp" = "x${command_check,,}" ]; then
  "$fixvid_dir/usage" $(basename $0);
  exit;
fi

if [ ! -x "$fixvid_dir/$command_check" ]; then
  "$fixvid_dir/usage" $(basename $0);
  cat <<NONCMD | cat;

    $command_check is not a valid $(basename $0) command.

    For available commands, use:
    $ $(basename $0) help

NONCMD
  exit;
fi

# Load the configuration file if it exists
[[ -s fixvid.conf ]] && . fixvid.conf;

# Create and export some text shortcuts to use later.
#
# ffmpeg for ignoring all but the chosen type of stream
export audio_only="-vn -sn -dn";
export video_only="-an -sn -dn";
export subtitles_only="-vn -an -dn";
# ffmpeg to ignore input timestamps, and force creation of new ones
export input_flags="-fflags +igndts";
export output_flags="-fflags +genpts";
# ffmpeg to leverage the multi-threading of the CPU, for aware libraries
export use_threads="-threads 64";
# ffmpeg to strip the metadata from the input file, except chapter times
export strip_meta_only="-map_metadata -1";
# ffmpeg to strip the metadata from the input file, including chapter times
export strip_meta_all="-map_metadata -1 -map_chapters -1";
export file_meta="-metadata creation_time='$timestamp' \
-metadata language=eng -metadata title=\"$video_title\""

# Call the command passed in, forwarding all other command line args
$fixvid_dir/$command_check "$@";
