#!/bin/bash

########################################################################
#                                                                      #
#  hts-split: extract individual channel sound files from source       #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

##
##      NOTE:
##
##  This file is only set up for processing of files related to a
##  surround sound soundtrack of either 5.1 or 5.1(side). Any other type
##  of surround sound setup, 7.1, etc., will require a complete set of
##  command files to replace hts-split, hts-normalize, and hts-merge
##

#
# Command script to extract the surround sound from a file and separate
# the channels into independent files for later processing. Also saves
# the original surround sound soundtrack to external files.
#
# Accepts no arguments.
#
# Reads fixvid.conf for:
#     work_files      the prefix of filenames for work files
#     video_title     added to the title metadata of the files
#     surround_source file with the surround sound stream to use
#     surround_stream the index (zero-based) of the surround stream
#     surround_layout the name of the layout, as understood by ffmpeg
#     channels        the filter used to split the stream into channels
#     timestamp       entered in the creation_time metadata for streams
#
# Displays the ffmpeg progress line while running and the results of the
# time command once finished.
#
# Generates 10 files:
#     fixvid_*_split.cmd      The complete ffmpeg command to execute
#     fixvid_*_split.log      The captured output of the ffmpeg command
#     *_surround_fc.wav       The front center channel from the source
#     *_surround_fl.wav       The front left channel from the source
#     *_surround_fr.wav       The front right channel from the source
#     *_surround_lf.wav       The low frequency channel from the source
#     *_surround_sl.wav       The surround left channel from the source
#     *_surround_sl.wav       The surround right channel from the source
#     *_surround.aac          The copied surround soundtrack, AAC format
#     *_surround.ac3          The copied surround soundtrack, AC3 format
#

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Set the output filename base
work_prefix="${work_files}_surround";

# Skip this if it has already been done.
# To rerun, delete the *_surround_fc.wav file first
[[ -s "${work_prefix}_fc.wav" ]] && exit 3;

time bash -c "FFREPORT=file=\"fixvid_${work_prefix}_split.log\":level=40 \
ffmpeg -hide_banner -y -loglevel error -stats \
$input_flags -i \"$surround_source\" \\
-filter_complex '\
  [0:$surround_stream] asplit=3 [CHANNELS][INTERNAL][EXTERNAL];\
  [CHANNELS] channelsplit=channel_layout=$surround_layout [FL][FR][FC][LF][SL][SR]\
' \
-map [FC] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Center Front Channel' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${work_prefix}_fc.wav\" \
-map [FL] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Left Front Channel' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${work_prefix}_fl.wav\" \
-map [FR] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Right Front Channel' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${work_prefix}_fr.wav\" \
-map [LF] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Low-frequency Channel' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${work_prefix}_lf.wav\" \
-map [SL] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Left Surround Channel' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${work_prefix}_sl.wav\" \
-map [SR] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Right Surround Channel' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${work_prefix}_sr.wav\" \
-map [EXTERNAL] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='5.1 Surround' \
-c:0 ac3 -b:a 640k \
$audio_only $use_threads $output_flags \
\"${work_prefix}.ac3\" \
-map [INTERNAL] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='5.1 Surround' \
-c:0 libfdk_aac -profile:a aac_he -b:a 384k \
$audio_only $use_threads $output_flags \
\"${work_prefix}.aac\"";
