#!/bin/bash

########################################################################
#                                                                      #
#  hts-normalize: apply dynaudnorm filter of ffmpeg to channel files   #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

##
##      NOTE:
##
##  This file is only set up for processing of files related to a
##  surround sound soundtrack of either 5.1 or 5.1(side). Any other type
##  of surround sound setup, 7.1, etc., will require a complete set of
##  command files to replace hts-split, hts-normalize, and hts-merge
##

#
# Command script to normalize each of the independent channel files from
# the surround sound soundtrack. Uses the files created by hts-split.
# If any of the 6 input files are missing, forces a run of hts-split.
#
# Accepts no arguments.
#
# Reads fixvid.conf for:
#     work_files      the prefix of filenames for work files
#     video_title     added to the title metadata of the files
#     timestamp       entered in the creation_time metadata for streams
#     dyna_center     the filter to apply to the center channel
#     dyna_front      the filter to apply to the left & right channels
#     dyna_surround   the filter to apply to other channels
# Reads the 6 channel files made by hts-split:
#     *_surround_fc.wav     The front center channel from the source
#     *_surround_fl.wav     The front left channel from the source
#     *_surround_fr.wav     The front right channel from the source
#     *_surround_lf.wav     The low frequency channel from the source
#     *_surround_sl.wav     The surround left channel from the source
#     *_surround_sr.wav     The surround right channel from the source
#
# Displays the ffmpeg progress line while running amd the results of the
# time command once finished.
#
# Generates 8 files:
#     fixvid_*_normal.cmd    The complete ffmpeg command to execute
#     fixvid_*_normal.log    The captured output of the ffmpeg command
#     *_surround_efc.wav     The front center channel from the source
#     *_surround_efl.wav     The front left channel from the source
#     *_surround_efr.wav     The front right channel from the source
#     *_surround_elf.wav     The low frequency channel from the source
#     *_surround_esl.wav     The surround left channel from the source
#     *_surround_esl.wav     The surround right channel from the source
#

# Load the configuration file
test -s fixvid.conf && . fixvid.conf || exit 4;

# Set the output filename base
surround_prefix="${work_files}_surround";

# Skip this if it has already been done.
# To rerun, delete the *_split_fc.wav file first
if [ -s "${surround_prefix}_fce.wav" ]; then
  exit;
fi

if \
  [ ! -s "${surround_prefix}_fc.wav" ] || \
  [ ! -s "${surround_prefix}_fl.wav" ] || \
  [ ! -s "${surround_prefix}_fr.wav" ] || \
  [ ! -s "${surround_prefix}_lf.wav" ] || \
  [ ! -s "${surround_prefix}_sl.wav" ] || \
  [ ! -s "${surround_prefix}_sr.wav" ]; then
    rm -f "${surround_prefix}_fc.wav"
    fixvid "hts-split";
fi

time bash -c "FFREPORT=file=\"fixvid_${surround_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${surround_prefix}_fc.wav\" \
-map 0:0 -af \"$dyna_center\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${surround_prefix}_efc.wav\"";

cat "fixvid_${surround_prefix}.part" > "fixvid_${surround_prefix}.log";

time bash -c "FFREPORT=file=\"fixvid_${surround_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${surround_prefix}_fl.wav\" \
-map 0:0 -af \"$dyna_front\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${surround_prefix}_efl.wav\"";

cat "fixvid_${surround_prefix}.part" >> "fixvid_${surround_prefix}.log";

time bash -c "FFREPORT=file=\"fixvid_${surround_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${surround_prefix}_fr.wav\" \
-map 0:0 -af \"$dyna_front\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${surround_prefix}_efr.wav\"";

cat "fixvid_${surround_prefix}.part" >> "fixvid_${surround_prefix}.log";

time bash -c "FFREPORT=file=\"fixvid_${surround_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${surround_prefix}_lf.wav\" \
-map 0:0 -af \"$dyna_surround\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${surround_prefix}_elf.wav\"";

cat "fixvid_${surround_prefix}.part" >> "fixvid_${surround_prefix}.log";

time bash -c "FFREPORT=file=\"fixvid_${surround_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${surround_prefix}_sl.wav\" \
-map 0:0 -af \"$dyna_surround\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${surround_prefix}_esl.wav\"";

cat "fixvid_${surround_prefix}.part" >> "fixvid_${surround_prefix}.log";

time bash -c "FFREPORT=file=\"fixvid_${surround_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${surround_prefix}_sr.wav\" \
-map 0:0 -af \"$dyna_surround\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${surround_prefix}_esr.wav\"";

cat "fixvid_${surround_prefix}.part" >> "fixvid_${surround_prefix}.log";

rm -f "fixvid_${surround_prefix}.part"
