#!/bin/bash

########################################################################
#                                                                      #
#  hts-merge: combine individual channel files into one soundtrack     #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

##
##      NOTE:
##
##  This file is only set up for processing of files related to a
##  surround sound soundtrack of either 5.1 or 5.1(side). Any other type
##  of surround sound setup, 7.1, etc., will require a complete set of
##  command files to replace hts-split, hts-normalize, and hts-merge
##

#
# Command script to take the 6 channels and build the 5.1 surround sound
# for the video.
#
# Accepts no arguments.
#
# Reads fixvid.conf for:
#     work_files    the prefix of filenames for work files
#     video_title   added to the title metadata of the files
#     channels      the filter used to join the channels into one stream
#     timestamp     entered in the creation_time metadata for streams
# Reads the 6 channel files made by hts-normalize:
#     *_surround_efc.wav       The adjusted front center channel
#     *_surround_efl.wav       The adjusted front left channel
#     *_surround_efr.wav       The adjusted front right channel
#     *_surround_elf.wav       The adjusted low frequency channel
#     *_surround_esl.wav       The adjusted surround left channel
#     *_surround_esl.wav       The adjusted surround right channel
#
# Displays the ffmpeg progress line while running and the results of the
# time command once finished.
#
# Generates 2 file:
#     *_surround_adjusted.aac  The adjusted surround sound, AAC format
#     *_surround_adjusted.ac3  The adjusted surround sound, AC3 format
#

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Set the channels based on the chosen surround layout
if [[ '5.1(side)' == $surround_layout ]]; then
  channels=$channels_51_side;
elif [[ '5.1' == $surround_layout ]]; then
  channels=$channels_51;
fi

# Set the output filename base
work_prefix="${work_files}_surround";

# Skip this if it has already been done.
# To rerun, delete the *_surround_adjusted.ac3 file first
[[ -s "${work_prefix}_adjusted.ac3" ]] && exit 3;

# Check for all dependent files
# Force hts-normalize to (re)make all if one is missing
[[ ! -s "${work_prefix}_efc.wav" ]] || \
[[ ! -s "${work_prefix}_efl.wav" ]] || \
[[ ! -s "${work_prefix}_efr.wav" ]] || \
[[ ! -s "${work_prefix}_elf.wav" ]] || \
[[ ! -s "${work_prefix}_esl.wav" ]] || \
[[ ! -s "${work_prefix}_esr.wav" ]] && \
{
  rm -f "${work_prefix}_efc.wav";
  fixvid "hts-normalize";
}

time bash -c "FFREPORT=file=\"fixvid_${work_prefix}_merge.log\":level=40 \
ffmpeg -hide_banner -y -loglevel error -stats \
$input_flags -i \"${work_prefix}_efc.wav\" \
$input_flags -i \"${work_prefix}_efl.wav\" \
$input_flags -i \"${work_prefix}_efr.wav\" \
$input_flags -i \"${work_prefix}_elf.wav\" \
$input_flags -i \"${work_prefix}_esl.wav\" \
$input_flags -i \"${work_prefix}_esr.wav\" \
-filter_complex '\
  [1:0][2:0][0:0][3:0][4:0][5:0] amerge=inputs=6 [CHANNELS];\
  [CHANNELS] $channels [OUT];\
  [OUT] asplit [INTERNAL][EXTERNAL]\
' \
-map [EXTERNAL] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title=\"5.1 Surround (Enhanced)\" \
-c:0 ac3 -b:a 640k \
$use_threads $file_meta \
\"${work_prefix}_adjusted.ac3\" \
-map [INTERNAL] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title=\"5.1 Surround (Enhanced)\" \
-c:0 libfdk_aac -profile:a aac_he -b:a 384k \
$use_threads $file_meta \
\"${work_prefix}_adjusted.aac\"";
