#!/bin/bash

########################################################################
#                                                                      #
#  hts-downmix: create a stereo stream from a surround sound stream    #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to extract the surround sound from a file and convert
# it to stereo, and enhance the stereo, saving both the extracted and
# adjusted versions.
#
# Uses the stereo_mix variable from the fixvid.conf file to determine
# the mixing from the available channels.
#

# Set the output filename base
work_prefix="${work_prefix}-downmix";

# Skip this if it has already been done.
# To rerun, delete the *_stereo_adjusted.aac file first
[[ -s "${work_prefix}-norm.ac3" ]] && return 3;

# Always make, or replace, the adjusted versions of the remixed files.
# They are subject to repeated building until the "correct" sound is
# achieved.

[[ 1 = $skip_aac ]] || multi_launch "Normalize ${audio_label} AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-norm-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -filter_complex '[0:$audio_stream] $audio_mixing [STEREO];[STEREO] $audio_dyna_stereo [NORM]' -map [NORM] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='${audio_title} (Enhanced)' -c:0 libfdk_aac -profile:a aac_he -b:a 128k $audio_only $use_threads $output_flags '${work_prefix}-norm.aac'";
[[ 1 = $skip_ac3 ]] || multi_launch "Normalize ${audio_label} AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-norm-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -filter_complex '[0:$audio_stream] $audio_mixing [STEREO];[STEREO] $audio_dyna_stereo [NORM]' -map [NORM] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='${audio_title} (Enhanced)' -c:0 ac3 -b:a 192k $audio_only $use_threads $output_flags '${work_prefix}-norm.ac3'";

# Skip creation of either, or both, of the un-normalized remix versions
# if they have already been made. They are not "adjusted" in any way, so
# remaking them each time is wasted CPU cycles.

[[ 1 = $skip_aac ]] || [[ -s "${work_prefix}.aac" ]] || multi_launch "Downmix ${audio_label} AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -filter_complex '[0:$audio_stream] $audio_mixing [STEREO]' -map [STEREO] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_label' -c:0 libfdk_aac -profile:a aac_he -b:a 128k $audio_only $use_threads $output_flags '${work_prefix}.aac'";
[[ 1 = $skip_ac3 ]] || [[ -s "${work_prefix}.ac3" ]] || multi_launch "Downmix ${audio_label} AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i '$audio_source' -filter_complex '[0:$audio_stream] $audio_mixing [STEREO]' -map [STEREO] $strip_meta_all $file_meta -metadata:s:0 language=$audio_lang -metadata:s:0 title='$audio_label' -c:0 ac3 -b:a 192k $audio_only $use_threads $output_flags '${work_prefix}.ac3'";

wait;

