#!/bin/bash

########################################################################
#                                                                      #
#  hts-normalize: apply dynaudnorm filter of ffmpeg to channel files   #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

##
##      NOTE:
##
##  This file is only set up for processing of files related to a
##  surround sound soundtrack of either 5.1 or 5.1(side). Any other type
##  of surround sound setup, 7.1, etc., will require a complete set of
##  command files to replace hts-split, hts-normalize, and hts-merge
##

#
# Command script to normalize each of the independent channel files from
# the surround sound soundtrack. Uses the files created by hts-split.
# If any of the 6 input files are missing, forces a run of hts-split.
#
# Accepts no arguments.
#
# Reads fixvid.conf for:
#     work_files      the prefix of filenames for work files
#     video_title     added to the title metadata of the files
#     timestamp       entered in the creation_time metadata for streams
#     dyna_center     the filter to apply to the center channel
#     dyna_front      the filter to apply to the left & right channels
#     dyna_surround   the filter to apply to other channels
# Reads the 6 channel files made by hts-split:
#     *-surround-fc.wav     The front center channel from the source
#     *-surround-fl.wav     The front left channel from the source
#     *-surround-fr.wav     The front right channel from the source
#     *-surround-lf.wav     The low frequency channel from the source
#     *-surround-sl.wav     The surround left channel from the source
#     *-surround-sr.wav     The surround right channel from the source
#
# Displays the ffmpeg progress line while running and the results of the
# time command once finished.
#
# Generates 8 files:
#     fixvid-*-normal.cmd    The complete ffmpeg command to execute
#     fixvid-*-normal.log    The captured output of the ffmpeg command
#     *-surround-efc.wav     The front center channel from the source
#     *-surround-efl.wav     The front left channel from the source
#     *-surround-efr.wav     The front right channel from the source
#     *-surround-elf.wav     The low frequency channel from the source
#     *-surround-esl.wav     The surround left channel from the source
#     *-surround-esl.wav     The surround right channel from the source
#

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Set the output filename base
work_prefix="${work_files}-surround";

# Skip this if it has already been done.
# To rerun, delete the *_surround_fce.wav file first
[[ -s "${work_prefix}_efc.wav" ]] && exit 3;

# Check for all dependent files
# Force hts-split to (re)make all if one is missing
[[ ! -s "${work_prefix}-fc.wav" ]] || \
[[ ! -s "${work_prefix}-fl.wav" ]] || \
[[ ! -s "${work_prefix}-fr.wav" ]] || \
[[ ! -s "${work_prefix}-lf.wav" ]] || \
[[ ! -s "${work_prefix}-sl.wav" ]] || \
[[ ! -s "${work_prefix}-sr.wav" ]] && \
{
  rm -f "${work_prefix}-fc.wav";
  fixvid "hts-split";
}

time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${work_prefix}-fc.wav\" \
-map 0:0 -af \"$dyna_center\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${work_prefix}-efc.wav\"";

cat "fixvid-${work_prefix}.part" > "fixvid-${work_prefix}-normalize.log";

time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${work_prefix}-fl.wav\" \
-map 0:0 -af \"$dyna_front\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${work_prefix}-efl.wav\"";

cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";

time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${work_prefix}-fr.wav\" \
-map 0:0 -af \"$dyna_front\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${work_prefix}-efr.wav\"";

cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";

time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${work_prefix}-lf.wav\" \
-map 0:0 -af \"$dyna_surround\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${work_prefix}-elf.wav\"";

cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";

time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${work_prefix}-sl.wav\" \
-map 0:0 -af \"$dyna_surround\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${work_prefix}-esl.wav\"";

cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";

time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.part\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"${work_prefix}-sr.wav\" \
-map 0:0 -af \"$dyna_surround\" \
-c:0 pcm_s16le -b:a 384k \
$use_threads $output_flags \
\"${work_prefix}-esr.wav\"";

cat "fixvid-${work_prefix}.part" >> "fixvid-${work_prefix}-normalize.log";

rm -f "fixvid-${work_prefix}.part"
