#!/bin/bash

########################################################################
#                                                                      #
#  hts-explode: extract individual channel sound files from source     #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to extract the surround sound from a file and separate
# the channels into independent files for later processing. Also saves
# the original surround sound soundtrack to external files.
#

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Check for source file and replace with common source if missing
if [[ 'x' == "x$surround_source" ]] && [[ -s $video_source ]]; then
  surround_source=$video_source;
fi

# Set the output filename base
work_prefix="${work_files}-surround";

# Skip this if it has already been done.
# To rerun, delete the *_surround_fc.wav file first
[[ -s "${work_prefix}-fc.wav" ]] && exit 3;

# Set the channel data based on the chosen surround layout
# Invalid, or missing, layout will abort the process
case "$surround_layout" in
  '7.1' )
    channel_map=$channel_map_71
    channel_list=$channel_list_71
    stereo_mix=$stereo_mix_71
    ;;
  '5.1' )
    channel_map=$channel_map_51
    channel_list=$channel_list_51
    stereo_mix=$stereo_mix_51
    ;;
  '5.1(side)' )
    channel_map=$channel_map_51_side
    channel_list=$channel_list_51_side
    stereo_mix=$stereo_mix_51_side
    ;;
  * )
    exit 3
    ;;
esac

encoding="$strip_meta_all $file_meta -metadata:s:0 language=eng -c:0 pcm_s16le -b:a 384k $audio_only $use_threads $output_flags";

for channel in $channel_list; do
  channel_pad="[${channel^^}]";
  pad_list="${pad_list}${channel_pad}";
  channel_out="-map [${channel^^}] $encoding '${work_prefix}-${channel}.wav'"
  out_list="${out_list} ${channel_out}";
done

multi_launch "Channel split" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-channels.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -filter_complex '[0:$surround_stream] channelsplit=channel_layout=$surround_layout $pad_list' $out_list";
multi_launch "Original AC3" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-ac3.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -map 0:$surround_stream $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround' -c:0 ac3 -b:a 640k $audio_only $use_threads $output_flags '${work_prefix}.ac3'";
multi_launch "Original AAC" bash -c "FFREPORT=file='fixvid-${work_prefix}-split-aac.log':level=40 ffmpeg -hide_banner -y -loglevel error -stats $input_flags -i $surround_source -map 0:$surround_stream $strip_meta_all $file_meta -metadata:s:0 language=eng -metadata:s:0 title='$surround_layout Surround' -c:0 libfdk_aac -profile:a aac_he -b:a 384k $audio_only $use_threads $output_flags '${work_prefix}.aac'";

wait

