#!/bin/bash

########################################################################
#                                                                      #
#  init: prep a directory for processing with fixvid commands          #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to initialize the working directory for using FixVid in
# it. Copies the configuration template to the working directory naming
# it fixvid.conf. Will not overwrite an existing file of that name. Also
# searches the directory for all files with .mp4, .mkv, .avi, .ac3, and
# .aac extensions, assuming they may contain video or sound that is of
# use in the process. All files, including symlinks, found are passed to
# the ffprobe command, and the pertinent results displayed to the user
# and saved into the fixvid.scan file for later reference.
#

test -s fixvid.conf || cp "$fixvid_dir/config-template" fixvid.conf;

if [[ -s "movie" ]]; then
  echo "";
  echo "********************************************************************************" | tee -a "fixvid.scan";
  echo "    Reading movie:" | tee -a "fixvid.scan";
  echo "--------------------------------------------------------------------------------" | tee -a "fixvid.scan";
  $fixvid_dir/explore "movie" | tee -a "fixvid.scan";
  echo "" | tee -a "fixvid.scan";
  echo "" | tee -a "fixvid.scan";
fi

for file_type in "mp4" "mkv" "avi" "aac" "ac3" "wav" "mp3"; do
  for filename in *.$file_type; do
    if [ -s "$filename" ]; then
      echo "";
      echo "********************************************************************************" | tee -a "fixvid.scan";
      echo "    Reading $filename:" | tee -a "fixvid.scan";
      echo "--------------------------------------------------------------------------------" | tee -a "fixvid.scan";
      $fixvid_dir/explore "$filename" | tee -a "fixvid.scan";
      echo "" | tee -a "fixvid.scan";
      echo "" | tee -a "fixvid.scan";
    fi
  done
done
