#!/bin/bash

########################################################################
#                                                                      #
#  stereo: extract a stereo soundtrack from a souce and modify it      #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to extract, and enhance, the stereo soundtrack from a
# file.
#
# Accepts no arguments.
#
# Reads fixvid.conf for:
#     work_files      the prefix of filenames for work files
#     video_title     added to the title metadata of the files
#     stereo_source   file with the stereo stream to use
#     stereo_stream   the index (zero-based) of the stereo stream
#     dyna_stereo     the filter to use for enhancing the stereo stream
#     timestamp       entered in the creation_time metadata for streams
#
# Displays the ffmpeg progress line while running amd the results of the
# time command once finished.
#
# Generates 6 files:
#     fixvid_*_stereo.cmd     The complete ffmpeg command to execute
#     fixvid_*_stereo.log     The captured output of the ffmpeg command
#     *_stereo.aac            The copied stereo soundtrack, AC3 format
#     *_stereo.ac3            The copied stereo soundtrack, AC3 format
#     *_stereo_adjusted.aac   The adjusted soundtrack, AAC format
#     *_stereo_adjusted.ac3   The adjusted soundtrack, AC3 format
#

##
##      NOTE:
##
##  The script will recreate all 4 soundtrack files everytime it is run.
##  The performance hit for recreating the 2 un-adjusted stereo files
##  is negligible compared to the speed of encoding only the adjusted
##  versions, and does not justify the increased complexity of scripting
##  to exclude them on reruns
##
##      NOTE:
##
##  The stereo and hts-stereo commands create the same group of files,
##  and will overwrite the other's output. Only one stereo soundtrack is
##  needed, and selecting the best available for use while ignoring all
##  others will avoid any complications from the two commands creating
##  the same group of files.
##

# Load the configuration file
test -s fixvid.conf && . fixvid.conf || exit 4;

# Set the output filename base
stereo_prefix="${work_files}_stereo";

# Skip this if it has already been done.
# To rerun, delete the *_stereo_adjusted.aac file first
if [ -s "${stereo_prefix}_adjusted.aac" ]; then
  exit;
fi

time bash -c "FFREPORT=file=\"fixvid_${stereo_prefix}.log\":level=40 \
ffmpeg -hide_banner -y -loglevel error -stats \
$input_flags -i \"$stereo_source\" \
-filter_complex '\
  [0:$stereo_stream] asplit=4 [AAC][AC3][WAV][IN];\
  [IN] $dyna_stereo [NORM];\
  [NORM] asplit=3 [AACe][AC3e][WAVe]\
' \
-map [AAC] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Stereo' \
-c:0 libfdk_aac -profile:a aac_he -b:a 128k \
$audio_only $use_threads $output_flags \
\"${stereo_prefix}.aac\" \
-map [AC3] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Stereo' \
-c:0 ac3 -b:a 192k \
$audio_only $use_threads $output_flags \
\"${stereo_prefix}.ac3\" \
-map [WAV] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Stereo' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${stereo_prefix}.wav\" \
-map [AACe] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Stereo (Enhanced)' \
-c:0 libfdk_aac -profile:a aac_he -b:a 128k \
$audio_only $use_threads $output_flags \
\"${stereo_prefix}_adjusted.aac\" \
-map [AC3e] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Stereo (Enhanced)' \
-c:0 ac3 -b:a 192k \
$audio_only $use_threads $output_flags \
\"${stereo_prefix}_adjusted.ac3\" \
-map [WAVe] \
$strip_meta_all $file_meta \
-metadata:s:0 language=eng -metadata:s:0 title='Stereo (Enhanced)' \
-c:0 pcm_s16le -b:a 384k \
$audio_only $use_threads $output_flags \
\"${stereo_prefix}_adjusted.wav\"";
