#!/bin/bash

########################################################################
#                                                                      #
#  subtitles: script to create multiple subtitle versions              #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to launch subtitle creation commands with all the
# proper parameters set. May launch the extraction multiple times if
# there are multiple occurrences of the configuration variables.
#

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Load the helper functions and common settings
source "$fixvid_dir/helpers";

group='subs';
required='stream';
group_fields='source stream label title type lang';

# The function to extract the subtitle file(s)
function get_subtitles {
  # Check for, and set the source file
  [[ $subs_source ]] || subs_source="$video_source";
  # Check for, and set the language for the subtitles
  [[ $subs_lang ]] || subs_lang="$video_lang";
  # Set the output filename base
  work_prefix="${work_files}-subs-$subs_label";

  case ${subs_type,,} in
    text|subrip|srt|ass|aas  )
      source "$fixvid_dir/extract-subtitles-text"
      ;;
    dvd_sub*|vobsub )
      source "$fixvid_dir/extract-subtitles-dvd"
      ;;
    * )
      exit 3
      ;;
  esac
}

# Read the optional argument.
[[ $1 ]] && target_num=$1 || target_num=0;

process_group get_subtitles $group $required $target_num $group_fields;

wait;
