#!/bin/bash

########################################################################
#                                                                      #
#  subtitles-dvd: copy dvd_subtitles format subtitels from a souce     #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2019  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to copy the subtitles in dvd_subtitle format from the
# source file creating a stand-alone MKV file to hold them for eventual
# inclusion in the finished product.
# Because of the need to make multiple versions of subtitles, this will
# require a separate launcher with the ability to discriminate the
# variables from the config file and options from the command line.
#
# Accepts no arguments:
#
# Reads fixvid.conf for:
#     work_files      the prefix of filenames for work files
#     video_title     added to the title metadata of the files
#     timestamp       entered in the creation_time metadata for streams
#
# Displays the ffmpeg progress line while running and the results of the
# time command once finished.
#
# Generates 1 file:
#     *-<label>.mkv   The copied subtitles in dvd_subtitle format
#                     <label>
#

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || return 4;

# Check for source file and replace with common source if missing
if [[ 'x' == "x$subs_source" ]] && [[ -s $video_source ]]; then
  subs_source=$video_source;
fi

# Set the output filename base
work_prefix="${work_files}-subs-$subs_label";

# Skip this if it has already been done.
# To rerun, delete the created .ass file first
[[ -s "${work_prefix}.mkv" ]] && return 3;

time bash -c "FFREPORT=file=\"fixvid-${work_prefix}.log\":level=40 \
ffmpeg -hide_banner -loglevel error -stats -y \
$input_flags -i \"$subs_source\" \
$strip_meta_all \
-map 0:$subs_stream \
-c:0 copy \
$subtitles_only $use_threads $output_flags \
\"$work_prefix.mkv\"";
