#!/bin/bash

########################################################################
#                                                                      #
#  subtitles: script to create multiple subtitle versions              #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Ronald Lamoreaux <code@chindraba.work>      #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to launch subtitle creation commands with all the
# proper parameters set. May launch the extraction multiple time if
# there are multiple occurrences of the configuration variables.
#
# Accepts 1 optional argument:
#     group_num   Which setting group to use in extraction.
#                 A value of "0", or no argument, will cycle through
#                 all the available groups, creating subtitles for each.
#                 Any other number will create one subtitle file using
#                 the group number to determine which settings to use.
#
# Reads fixvid.conf for:
#     subs_source_n
#     subs_stream_n
#     subs_label_n
#     subs_title_n
#     subs_type_n
#     _n
#         where "n" is an integer number beginning at "1"
#
# Displays nothing.
#
# Generates 0 files:
#

group='subs';
required='stream';
group_fields='source stream label title type included';

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Read the optional argument.
[[ $1 ]] && traget_num=$1 || traget_num=0;

# The function to extract the subtitle file(s)
function get_subtitles {
  case ${subs_type,,} in
    'text' )
      source "$fixvid_dir/subtitles-text"
      ;;
    'dvd_subtitle' | \
    'dvd_subtitles' )
      source "$fixvid_dir/subtitles-dvd"
      ;;
    * )
      exit 3
      ;;
  esac
}

process_group get_subtitles $group $required $traget_num $group_fields;


