#!/bin/bash

########################################################################
#                                                                      #
#  titles: functions to create multiple subtitle versions              #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018, 2019  Chindraba (Ronald Lamoreaux)                #
#                          <fixvid@chindraba.work>                     #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

function titles_build {
  local titles_codec="${1:-copy}";
  local titles_ext="${2:-mkv}";
  [[ ! -s "${current_base}.$titles_ext" ]] || check $force_run || \
    return 0;
  build_ffmpeg_preamble "${current_base}.$titles_ext";
  codec_part="-c:0 $titles_codec";
  build_ffmpeg_stream;
  build_ffmpeg_output "$titles_ext" "$subtitles_only";
  build_ffmpeg_command;
  shared_launch "${current_title} Subtitles" \
    "${current_label}_titles" bash -c "$ffmpeg_command";
  reset_ffmpeg_data;
  return 0;
}

function titles_extract {
  case ${current_type,,} in
    text|subrip|srt|ass|aas  )
      titles_build "ass" "ass";
      ;;
    dvd_sub*|vobsub )
      titles_build;
      ;;
    * )
      return 0
      ;;
  esac
  return 0;
}

titles_key='stream';
titles_fields="source stream label lang title type include SDH \
file save";

# ffmpeg for ignoring all but the chosen type of stream
subtitles_only="-vn -an -dn";

usage['[t] titles']='[<target_num>] Extract/process the subtitle stream(s)';
function titles_help {
  cat <<HELP_SUBTITLES

    titles [<target_num> [<force>]]
        Create subtitle files from the files and streams identified in
        the fixvid.conf file. Multiple streams can be created. For more
        information on multiple streams, see: $1 help target_num.

HELP_SUBTITLES
}

function titles_config {
tee -a 'fixvid.conf' << 'EOtitles' >/dev/null

########################################################################
#                                                                      #
#                      Subtitle component settings                     #
#                                                                      #
########################################################################

#
#  File that has the subtitles to use as the final subtitle stream
#= titles_source_1='movie';
#= titles_file_1='title.srt';
titles_stream_1=;

#  The label used in the filename to separate one set of subtitles from
#+ any others.
#+ For text-based subtitles, will also be used as the suffix for the
#+ final product as the generated subtitles are saved in external ASS
#+ and SRT files for use in players which need them. File name will be
#+ something like:
#+       The_Movie_Name-CHI.srt
#+ for the case of titles_label set to CHI. The one exception to this is
#+ if the titles_label value is exactly DEFAULT, in which case the suffix
#+ will omitted. Many video players will take a subtitle file with the
#+ same name as the video file and consider them to be the set to load
#+ automatically
titles_label_1='titles';

#  The 3-letter language code for the language the subtitles are in
titles_lang_1='eng';

#  The title of the subtitles, as shown by most media players when the
#+ user selects subtitles from the menu
titles_title_1='Standard subtitles';
#  What type of subtitles the souce file contains. Text is for SRT, AAS,
#+ and ASS.
titles_type_1='dvd_subtitle';
#  Are these subtitles to be included in the final product video?
#+ Leave commented to prevent them from being included.
titles_include_1=1;

#  Setting to show that this is a 'Hearing-Impaired' subtitle stream.
#+ Not required, but having it set will allow the stream to be marked as
#+ Hearing-Impaired in the final product in the event that a player is
#+ set up to always choose such subtitles over other defaults.
#= titles_SDH_1=1;

#  Whether or not to save a copy of this stream during the finalization
#= titles_save_1=1;

#  Additional sets of subtitles may be created by using increasing
#+ numbers for each set of parameters. All parameters are needed for the
#+ system to create the subtitles described.
#= titles_source_2='movie.mkv';
#= titles_file_2='titles-CHI.srt'
#= titles_stream_2=3;
#= titles_label_2='DEFAULT';
#= titles_title_2='Standard Subtitles';
#= titles_type_2='text';
#= titles_include_2=1;
#= titles_SDH_2=1;
#= titles_save_2=1;

EOtitles
}
