#!/bin/bash

########################################################################
#                                                                      #
#  usage: print usage and help information for the FixVid program      #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

# Command script to show the help/usage information for the FixVid
# project
#
# Accepts no arguments
#
# Displays, on STDOUT, the usage data
#
# Generates no files
#

show_usage='cat';
test -n $PAGER && show_usage="$PAGER";

cat <<USAGE | "$show_usage";
Usage: $1 <command> [arg [arg [...] ] ]

Processs files in the current directory, according to the information in
the fixvid.conf file as steps in creating a video file from the source
file(s).

Available commands are:

    dts-build
        Create DTS formatted surround sound files from the previously
        created AC3 files from hts-merge.

    explore <file>
        run ffprobe on the listed file and filter the results, showing
        the lines pertinent to the file's duration, chapter list, and
        each stream located in the file.

    hts-merge
        Combine individual channel files into a single 5.1 surround
        sound soundtrack, saving internal use and external copies of the
        adjusted soundtrack. If any of the needed files are abscent,
        will force a run of hts-normalize.

    hts-normalize
        Apply normalization filters to each of the 5.1 surround sound
        channel files made by hts-split. Then adjusted versions are the
        expected input to hts-merge. If any of the needed files are
        absent, will force a run of hts-split.

    hts-split
        Extract the 5.1 surround sound soundtrack from the file, save
        the unmodified versions and split the soundtrack into individual
        channel files for further processing via hts-normalize and
        hts-merge.

    hts-stereo
        Create a stereo soundtrack from the 5.1 surround sound
        soundtrack, save unadjusted versions and adjusted versions of
        the new stereo soundtrack.

    init
        Create the empty fixvid.conf file in the directory and scan for
        all .mp4, .mkv, and .avi files in the current directory and
        provide a filtered output from ffprobe for each. The scan
        results are displayed, and recorded in the fixvid.scan file.

    subtitles [<group_num>]
        Create subtitle files from the files and streams identified in
        the fixvid.conf file. Will make multiple versions of the
        subtitles if the settings in the config file call for it.
        <group_num> is a number from 1 to whatever, and corresponds to
        the subs_?_x settings in the config file. The numbers must begin
        at 1, and have no gaps in the sequence. The first group of
        settings without a source will cause the sequence to end prior
        to that number. If fixvid subtitles is called with an argument
        of zero, or no argument, then all the versions will be created,
        otherwise only the version which matches the argument will be
        built, if it is valid in the number sequence.

    rebuild [<group_num>]
        Create video files from the files and streams identified in the
        fixvid.conf file. Will make multiple versions of the video if
        the settings in the config file call for it. <group_num> is a
        number from 1 to whatever, and corresponds to the video_?_x
        settings in the config file. The numbers must begin at 1, and
        have no gaps in the sequence. The first group of settings
        without a codec will cause the sequence to end prior to that
        number. If fixvid rebuild is called with an argument of zero, or
        no argument, then all the versions will be created, otherwise
        only the version which matches the argument will be built, if it
        is valid in the number sequence.

    stereo
        Extract the stereo sound track from the file and stream
        identified in the fixvid.conf file as the stereo source. Applies
        the enhancements to the stereo sound track and creates an .aac
        and .ac3 file of the original and the enhanced soundtracks.

    video [<group_num>]
        Extract the video from the file and stream identified in the
        fixvid.conf file. Will make multiple copies of the video if the
        settings in the config file call for it. <group_num> is a number
        from 1 to whatever, and corresponds to the video_?_x settings in
        the config file. The numbers must begin at 1, and have no gaps
        in the sequence. The first group of settings without a codec
        will cause the sequence to end prior to that number. If fixvid
        video is called with an argument of zero, or no argument, then
        all the versions will be extracted, otherwise only the version
        which matches the argument will be built, if it is valid in the
        number sequence.

USAGE

if [ 'cat' == $show_usage ]; then
  echo '------------------------------------------------------------------------';
fi

