#!/bin/bash

########################################################################
#                                                                      #
#  video: script to control the extraction of multiple video versions  #
#                                                                      #
#  This file is part of FixVid, a system to semi-automatically modify  #
#  and re-encode video files to create an acceptable version for a     #
#  standardized collection or library of videos.                       #
#                                                                      #
#  Copyright © 2018  Ronald Lamoreaux <code@chindraba.work>            #
#  - All Rights Reserved                                               #
#                                                                      #
#  FixVid is free software; you can redistribute it and/or             #
#  modify it under the terms of the GNU General Public License,        #
#  version 2 only, as published by the Free Software Foundation.       #
#                                                                      #
#  FixVid is distributed in the hope that it will be useful,           #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of      #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the       #
#  GNU General Public License for more details.                        #
#                                                                      #
#  You should have received a copy of the GNU General Public License   #
#  along with this program; if not, write to the                       #
#        Free Software Foundation, Inc.                                #
#        51 Franklin Street                                            #
#        Fifth Floor                                                   #
#        Boston, MA  02110-1301                                        #
#        USA.                                                          #
#                                                                      #
########################################################################

#
# Command script to launch extract_video with all the proper parameters
# set. May launch the extraction multiple time if there are multiple
# occurrences of the video configuration variables.
#
# Accepts 1 optional argument:
#     group_num   Which setting group to use in extraction.
#                 A value of "0", or no argument, will cycle through
#                 all the available groups, extracting a video for
#                 each. Any other number will extract one video,
#                 using the group number to determine which one to
#                 use.
#
# Reads fixvid.conf for:
#     video_label_n
#     video_codec_n
#     video_params_n
#     video_equalizer_n     The eq video filter settings
#     video_adjust_n
#     video_complex_n
#         where "n" is an integer number beginning at "1"
#
# Displays nothing.
#
# Generates 0 files:
#

group='video';
required='codec';
group_fields='label codec params equalizer adjust complex';

# Load the configuration file
[[ -s fixvid.conf ]] && . fixvid.conf || exit 4;

# Read the optional argument.
[[ $1 ]] && traget_num=$1 || traget_num=0;

# The function to extract the video file(s)
function get_video {
  source "$fixvid_dir/extract-video";
}

process_group get_video $group $required $traget_num $group_fields;
